# Generated by Django 3.2.7 on 2021-09-10 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('z_example_apiview', '0002_rename_modelforapiview_example1'),
    ]

    operations = [
        migrations.AddField(
            model_name='example1',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
